/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contasreceber.messaging;

import java.text.MessageFormat;

import org.springframework.amqp.core.Queue;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import br.com.kerubin.api.financeiro.contasreceber.FinanceiroContasReceberConstants;
import br.com.kerubin.api.messaging.core.DomainEventConstants;

@ComponentScan({"br.com.kerubin.api.messaging.core"})
@Configuration
public class FinanceiroContasReceberEventConfig {
	
	public static final String FINANCEIRO_CONTAS_RECEBER_QUEUE = "financeiroContasReceberQueue";
	
	@Bean
	public Queue financeiroContasReceberQueue() {
		// Default queue for this service.
		String queueName = MessageFormat.format("{0}_{1}_{2}", //
			DomainEventConstants.APPLICATION, //
			FinanceiroContasReceberConstants.DOMAIN, //
			FinanceiroContasReceberConstants.SERVICE); //
		
		return new Queue(queueName, true);
	}

}

