/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contasreceber.messaging;

import br.com.kerubin.api.messaging.core.DomainMessage;

public interface FinanceiroContasReceberEventHandler {

	void handleEvent(DomainMessage message);

}

