/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contasreceber.entity.contareceber;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ContaReceberAutoCompleteImpl implements ContaReceberAutoComplete {

	private java.util.UUID id;
	
	private String descricao;
	
	public ContaReceberAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
