/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contasreceber.entity.cliente;

import com.querydsl.core.types.Predicate;

public interface ClienteListFilterPredicate {
	
	Predicate mountAndGetPredicate(ClienteListFilter clienteListFilter);

}

